### ISSUE TITLE
Detect kustomization and Helm changes in case it's reference by another repo

### ISSUE THREAD

**Issue by chandankumar4** [numaproj-labs/numaplane#100]
# Summary

What change needs making?

# Use Cases

When would you use this?

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by xdevxy** [comment]
For this task, we can go with simple approach initially to calculate the manifests each iteration and provide an option for it to enable or disable.
