### ISSUE TITLE
Attempt reconnect to git repositories in the case of Credentials having changed

### ISSUE THREAD

**Issue by juliev0** [numaproj-labs/numaplane#108]
# Summary

Want to add this issue to ensure that we take care of this case. If we are reading from a repository and the Credentials in our ConfigMap have changed, we need to make sure we use the new Credentials and reconnect. 

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by shubhamdixit863** [comment]
Two issues need to be addressed here:

1. We haven't added git authentication while making a fetch in the [`watchRepo`](https://github.com/numaproj-labs/numaplane/blob/e94a27ba4151b3988011346ae8c8a76720c97c07/internal/git/gitsync_processor.go#L118) function, as `watchRepo` has this ticker running in a [for loop](https://github.com/numaproj-labs/numaplane/blob/e94a27ba4151b3988011346ae8c8a76720c97c07/internal/git/gitsync_processor.go#L216), which [calls](https://github.com/numaproj-labs/numaplane/blob/e94a27ba4151b3988011346ae8c8a76720c97c07/internal/git/gitsync_processor.go#L231C42-L231C61) `CheckForRepoUpdates`. Inside this function, we are making a [call](https://github.com/numaproj-labs/numaplane/blob/e94a27ba4151b3988011346ae8c8a76720c97c07/internal/git/gitsync_processor.go#L361) to [`fetchUpdates(r)`](https://github.com/numaproj-labs/numaplane/blob/e94a27ba4151b3988011346ae8c8a76720c97c07/internal/git/gitsync_processor.go#L503), which in turn calls [`git remote.Fetch`](https://github.com/numaproj-labs/numaplane/blob/e94a27ba4151b3988011346ae8c8a76720c97c07/internal/git/gitsync_processor.go#L509). We need to pass authentication in the `FetchOptions` too, which has not yet been covered.

2. Now, let's say if the config changes while checking for updates in the repo, what we need to do is create a `GetRepoFetchOptions` method, which we will call in the [`CheckForRepoUpdates`](https://github.com/numaproj-labs/numaplane/blob/e94a27ba4151b3988011346ae8c8a76720c97c07/internal/git/gitsync_processor.go#L357) method, which is automatically called in the loop in the `watchRepo` method.

Now the fun part: We already have a [`GlobalConfig`](https://github.com/numaproj-labs/numaplane/blob/e94a27ba4151b3988011346ae8c8a76720c97c07/internal/git/gitsync_processor.go#L357) in [`ConfigManager`](https://github.com/numaproj-labs/numaplane/blob/e94a27ba4151b3988011346ae8c8a76720c97c07/internal/controller/config/config.go#L13), which will be updated by viper [here](https://github.com/numaproj-labs/numaplane/blob/e94a27ba4151b3988011346ae8c8a76720c97c07/internal/controller/config/config.go#L92). All we need to do now is call `GetConfigManager` in `CheckForRepoUpdates`, something like below:

```markdown
func CheckForRepoUpdates(ctx context.Context, r *git.Repository, repo *v1alpha1.RepositoryPath, lastCommitHash string, defaultNamespace string) (PatchedResource, string, error) {
    var patchedResources PatchedResource
    var recentHash string
    // Call get repo fetch options here and get the latest global config from the controller
    getConfig, err := controllerconfig.GetConfigManagerInstance().GetConfig() // this returns the updated global config
    if err != nil {
        return PatchedResource{}, "", err
    }
    fetchOptions := GetRepoFetchOptions(getConfig)
    
    fetchUpdates(r, fetchOptions) // pass fetchOptions in fetchUpdates
}
```

```markdown
func GetRepoFetchOptions(ctx context.Context, repoCred *controllerconfig.RepoCredential, kubeClient kubernetes.Client, namespace string, repo *v1alpha1.RepositoryPath) (*git.FetchOptions, error) {
    if repoCred == nil {
        return nil, fmt.Errorf("repository credentials cannot be nil")
    }
    if repo == nil || repo.RepoUrl == "" {
        return nil, fmt.Errorf("repository URL cannot be empty")
    }

    endpoint, err := transport.NewEndpoint(repo.RepoUrl)
    if err != nil {
        return nil, fmt.Errorf("invalid repository URL: %w", err)
    }
    scheme, err := GetURLScheme(repo.RepoUrl)
    if err != nil {
        return nil,
}

**Comment by juliev0** [comment]
Thanks for laying all of this out and being so clear in your message. 

`getConfig.Repocredential` isn't real, right? That's just supposed to represent the credential for this repository path, right?

Regarding this:
```
if repoCred == nil {
        return nil, fmt.Errorf("repository credentials cannot be nil")
    }
```
...as mentioned in the other PR, note that of course it is fine to not have any credentials.

I don't think your `GetRepoFetchOptions()` is complete, right? How would it differ from `GetRepoCloneOptions()` and can some of that code be consolidated together as a single function?

Overall, your strategy seems good. I am kind of thinking about whether we can store in memory a hash of the ConfigMap or something, and then determine if that hash changed before we try to reprocess it.

**Comment by shubhamdixit863** [comment]
**...as mentioned in the other PR, note that of course it is fine to not have any credentials.**. yes right that has been incorporated i will modify my comment 

**getConfig.Repocredential** is an slice we will call [FindCredByURl](https://github.com/numaproj-labs/numaplane/blob/feat/gitAuthentication/internal/shared/git/git.go#L233)  post that

**GetRepoFetchOptions() is complete, right?**  for brevity i have omitted the details but it will work same as [GetRepoCloneOptions](https://github.com/numaproj-labs/numaplane/blob/feat/gitAuthentication/internal/shared/git/git.go#L152) but will return [FetchOptions](https://pkg.go.dev/github.com/src-d/go-git#FetchOptions.Auth)

**some of that code be consolidated together as a single function?** I doubt as of now but once i actually write code may be I can figure out the way .

**Comment by juliev0** [comment]
> **...as mentioned in the other PR, note that of course it is fine to not have any credentials.**. yes right that has been incorporated i will modify my comment
> 
> **getConfig.Repocredential** is an slice we will call [FindCredByURl](https://github.com/numaproj-labs/numaplane/blob/feat/gitAuthentication/internal/shared/git/git.go#L233) post that
> 
> **GetRepoFetchOptions() is complete, right?** for brevity i have omitted the details but it will work same as [GetRepoCloneOptions](https://github.com/numaproj-labs/numaplane/blob/feat/gitAuthentication/internal/shared/git/git.go#L152) but will return [FetchOptions](https://pkg.go.dev/github.com/src-d/go-git#FetchOptions.Auth)
> 
> **some of that code be consolidated together as a single function?** I doubt as of now but once i actually write code may be I can figure out the way .

Looks good. What do you think about this?:

> I am kind of thinking about whether we can store in memory a hash of the ConfigMap or something, and then determine if that hash changed before we try to reprocess it.

Maybe something like that could cut down on any unnecessary work?

**Comment by juliev0** [comment]
> Maybe something like that could cut down on any unnecessary work?

Well, I guess it really depends on how much work is being done. If it's not a lot, we don't need to worry about this optimization, at least for now.

**Comment by shubhamdixit863** [comment]
Ok I will create an issue post pr

**Comment by xdevxy** [comment]
Overall strategy looks good to me @shubhamdixit863 thanks for laying it out!
