### ISSUE TITLE
Implement TLS Authentication for Git Clone

### ISSUE THREAD

**Issue by shubhamdixit863** [numaproj-labs/numaplane#109]
# Summary
Implementing TLS authentication should ensure that all Git clone operations are performed over a secure channel. The implementation should verify the server's TLS certificate and establish a secure connection before proceeding with the clone operation.

What change needs making?
Add TLS authentication to [GetAutMethod](https://github.com/numaproj-labs/numaplane/blob/d992ca903e9c9510185794b17c1643f7aeab077f/internal/shared/gitconfig/gitconfig.go#L80)
Related issue -https://github.com/numaproj-labs/numaplane/issues/9
# Use Cases

When would you use this?

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by xdevxy** [comment]
Closed by #118
