### ISSUE TITLE
chore: re-enable the git authz test

### ISSUE THREAD

**Issue by xdevxy** [numaproj-labs/numaplane#129]
Re-enable the tests that are disabled during refactor for git authz.

_Originally posted by @xdevxy in https://github.com/numaproj-labs/numaplane/pull/124#discussion_r1510429413_

**Comment by shubhamdixit863** [comment]
This pr -https://github.com/numaproj-labs/numaplane/pull/125 covers this issue

**Comment by xdevxy** [comment]
Closed with https://github.com/numaproj-labs/numaplane/pull/125
