### ISSUE TITLE
Ensure delete a GitSync CR is handled correctly

### ISSUE THREAD

**Issue by xdevxy** [numaproj-labs/numaplane#137]
# Summary

When an existing GitSync CR gets delete, we need to all resources belongs to it are deleted together. This means when we an GitSync is deleted, we need to delete all the resources associated with it.

Particularly, we need to delete the resources at:
- during controller [reconciliation](https://github.com/numaproj-labs/numaplane/blob/main/internal/controller/gitsync_controller.go#L140), which means the GitSync may no longer be enqueued.
- during the [worker task execution](https://github.com/numaproj-labs/numaplane/blob/main/internal/sync/syncer.go#L210)
- after the worker task [finishes syncing](https://github.com/numaproj-labs/numaplane/blob/main/internal/sync/syncer.go#L242)

This ensures with a deleted gitsync after the last sync, all associated resources are deleted as the gitsync will not be enqueued again.

To retrieve the resources associated with the GitSync, we should utilize `LiveStateCache.GetManagedLiveObjs()`. Moreover, we may want to add an option in configmap to enable or disable cascading deletion.
 
Note that if `Not Found` error occur during deleting the resources, it should be ignored.

# Use Cases

Delete existing GitSync CRs

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by juliev0** [comment]
We need to come up with a good way to do this so as to not have any race conditions actually: if we do it in the reconciler when we notice the `DeletionTimestamp` [here](https://github.com/numaproj-labs/numaplane/blob/4349bca446c647882ec321201697ca609b7bacb6/internal/controller/gitsync_controller.go#L140), then what if at the same time we're basically at [this](https://github.com/numaproj-labs/numaplane/blob/4349bca446c647882ec321201697ca609b7bacb6/internal/sync/syncer.go#L221) line performing the sync?

**Comment by juliev0** [comment]
Okay, @xdevxy and I discussed that the `DeletionTimestamp` can be checked again after the sync to perform deletion there as well just in case that race condition occurs.

**Comment by xdevxy** [comment]
Yeah, since the gitsync will no longer be enqueued again and we just need to ensure after the last sync the resources are deleted in case it gets there.
