### ISSUE TITLE
Docker test image for GitServer 

### ISSUE THREAD

**Issue by juliev0** [numaproj-labs/numaplane#144]
# Summary

Create a Docker image to run Git Server to be used for unit test, e2e test, and potentially BDD test for AddOn, which can optionally mount a volume.  It can initialize 0-n repositories based on command line input. 

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by xdevxy** [comment]
Closed by #169
