### ISSUE TITLE
investigation into ArgoCD and Numaflow e2e testing

### ISSUE THREAD

**Issue by dpadhiar** [numaproj-labs/numaplane#148]

**Comment by vigith** [comment]
is there a document to share about this investigation?

**Comment by dpadhiar** [comment]
> is there a document to share about this investigation?

Yes, all included in the end of the e2e framework design document. Going to add a short summary per Hao's request to sum everything.

https://docs.google.com/document/d/16_de3AnGecPT-PQJQpVT05HOMQw3Wc6t7MxuRFbAcic/edit
