### ISSUE TITLE
Add Image build steps in CI process

### ISSUE THREAD

**Issue by chandankumar4** [numaproj-labs/numaplane#150]
# Summary

What change needs making?
- Add steps in CI to build Docker image, we can simply run command `make docker-build`

# Use Cases

When would you use this?
- For each PR/commit it should run, similar to unit-test and lint

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by a49ibrahim** [comment]
@whynowy @xdevxy @juliev0  while developing this I realized we need a  `{{ secrets.DOCKERHUB_USERNAME }}` and `{{ secrets.DOCKERHUB_PASSWORD }}`
