### ISSUE TITLE
Support for github proxy 

### ISSUE THREAD

**Issue by xdevxy** [numaproj-labs/numaplane#203]
# Summary

We need to add a transparent mapping internally to support case a github proxy is used for repo access. This means if the mapping is enabled 1) url in gitsync will translate to the pattern passed in from configmap 2) no credential will be used 

# Use Cases

When github proxy is used.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by juliev0** [comment]
> 2) no credential will be used

@xdevxy I think we're just looking for the url to be translated

**Comment by afugazzotto** [comment]
> > 2. no credential will be used
> 
> @xdevxy I think we're just looking for the url to be translated
> 
> I think it may have been a misunderstanding yesterday when we were talking that you thought I meant that? What I was saying was: currently, we essentially map a repository prefix to a set of Credentials that go with that repository prefix [here](https://github.com/numaproj-labs/numaplane/blob/main/internal/controller/config/config.go#L43). (The slice includes the prefix.) Want to let @afugazzotto know about that in case it makes sense to put the whole thing into one structure if it makes sense, or otherwise keep separate if that makes more sense.

When using the GitHub proxy, credentials are not needed since using mesh for authZ. We can either decide to skip credentials retrieval or leave it since the proxy will overwrite the authentication header.

**Comment by juliev0** [comment]
Yes. In the ConfigMap for Intuit, we won't include any credentials.

**Comment by xdevxy** [comment]
Closed as we chose alternative approach to use gitconfig
