### ISSUE TITLE
Support DLQ capability

### ISSUE THREAD

**Issue by mfongintuit** [numaproj-labs/numaplane#209]
Problem Statement: Today for Async event processing pipeline where multiple sinks are DB sink . The scenario when there is a DB issue for one of the sinks for an extended period ( a couple of hours ) would impact the entire pipeline.

Ask from customer is to support this use case and ensure that the scenario where there are  DB outages in the case of multi DB sinks does not impact the pipeline

Customer : Payroll team 

![Image](https://github.com/numaproj-labs/numaplane/assets/113948058/cd0db05d-7cf7-43da-9ea5-2a0a395ea252)

**Comment by vigith** [comment]
wrong repo. i will open a new one in numaflow.
