### ISSUE TITLE
add Validation logic for GitSync 

### ISSUE THREAD

**Issue by juliev0** [numaproj-labs/numaplane#22]
Need to make sure the GitSync CRD that's applied is valid (there's a placeholder - an empty validate() method - for it in the Controller).

Basically, need to go through the expected fields of the Spec and make sure they are populated in a valid way.

**Comment by shubhamdixit863** [comment]
Following Validations need to be checked 
1-repourl is valid or not by running git ls-remote using Go git library
2-Names can only contain lowercase alphanumeric characters, '-', and '.', but must start and end with an alphanumeric character. They cant contain names starting with kubernetes-, kube-, as these are reserved names.
3-targetRevision cannot be an empty string 
4-name for repositoryPaths cannot be empty string 
5-clusterName cannot be empty string
@juliev0 @xdevxy

**Comment by xdevxy** [comment]
Closed by #74
