### ISSUE TITLE
E2E test for gitsync from a branch other than `main` or `master`

### ISSUE THREAD

**Issue by xdevxy** [numaproj-labs/numaplane#248]
e2e test gitsync from a branch other than main or master. This may be 1) gitsync initially point to that branch. 2) gitsync points to main first and then a new branch is created, gitsync point to that new branch.

**Comment by dpadhiar** [comment]
Bug found while writing here: https://github.com/numaproj-labs/numaplane/issues/258

Blocked until it is fixed
