### ISSUE TITLE
Update souce of existing GitSync throw errors

### ISSUE THREAD

**Issue by xdevxy** [numaproj-labs/numaplane#276]
**Describe the bug**
Modifying already synced raw repo to helm or vice versa: 

`error: {"level":"error","worker":6,"gitSyncKey":"numaplane-system/gitsync-example","error":"failed to calculate diff: error calculating server side diff: serverSideDiff error: error removing non config mutations for resource Deployment/nginx: error reverting webhook removed fields in predicted live resource: .spec.template.spec.containers: element 0: associative list with keys may not have a null element","logger":"numaplane.synchronizer","caller":"sync/syncer.go:319","ts":"2024-05-03T07:26:50.049299319Z","msg":"Error on comparing git sync state"}`

**To Reproduce**
Modifying already synced raw repo to helm or vice versa

**Expected behavior**
No error should occur

**Screenshots**

**Environment (please complete the following information):**

- Kubernetes: [e.g. v1.18.6]

**Additional context**

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We often sort issues this way to know what to prioritize.

**Comment by chandankumar4** [comment]
I was testing it out again and figured out that it was failing due to deployment name of application was colliding, when I changed the deployment name in helm chart then it went smooth. I think it's not a but now, @xdevx what do you think?

**Comment by xdevxy** [comment]
Sounds good, close this issue then
