### ISSUE TITLE
Avoid multiple GitSync CRs watching the same git repo path

### ISSUE THREAD

**Issue by xdevxy** [numaproj-labs/numaplane#29]
It is possible there are multiple GitSync CRs mapping to the same git repo path and destination, which could potentially bring problems when the tracked commit hashes are different.

We would want to avoid that by either 1) checking at validation time or 2) prior to GitSyncProcessor creation. The former would be cleaner and sooner though.

**Comment by xdevxy** [comment]
Relates to #22

**Comment by juliev0** [comment]
@whynowy wanted to run this by you. Is there any reason why a K8S Controller shouldn't perform validation that's aware of other resources? Just want to make sure this isn't an anti-pattern or something.

**Comment by whynowy** [comment]
In terms of validation:

1. It's valid that multiple GitSync objects pointing same source repo/path;
2. It is not good to have multiple GitSync object deploying to same cluster/namespace. However, there's no good way to prevent that in the controller - when the controller detects that, it means the objects have been in etcd, and it's not easy to tell which one is valid. The way to validate it is using ValidatingAdmissionWebhook, but this is kind of best effort.

**Comment by juliev0** [comment]
> In terms of validation:
> 
> 1. It's valid that multiple GitSync objects pointing same source repo/path;
> 2. It is not good to have multiple GitSync object deploying to same cluster/namespace. However, there's no good way to prevent that in the controller - when the controller detects that, it means the objects have been in etcd, and it's not easy to tell which one is valid. The way to validate it is using ValidatingAdmissionWebhook, but this is kind of best effort.

The wording of this Issue is "mapping to the same git repo path **and** destination". This is the case we were concerned with. I feel that it's actually technically okay if they only have the same destination - if it's different resources being deployed.

**Comment by juliev0** [comment]
> 2\. there's no good way to prevent that in the controller 

Regarding this part of the statement - so I think if the Controller is already in a running state and then is notified of new GitSync A, followed by new GitSync B, it can look at its internal memory and knowledge of GitSync A in order to reject GitSync B. But maybe the issue is when the Controller restarts - it could be notified of each of them in any order and doesn't know to prioritize GitSync A over B - is that the issue?

**Comment by juliev0** [comment]
Per previous discussion, I think we should close this one

**Comment by xdevxy** [comment]
Close this issue based on above conversation.
