### ISSUE TITLE
Create GitSyncProcessor

### ISSUE THREAD

**Issue by juliev0** [numaproj-labs/numaplane#3]
Create a new GitSyncProcessor struct with creation functionality, as described in the design [doc](https://docs.google.com/document/d/1d1xVkVwCT4sGijiL0ymboEcLuKTqYcg8mHh_9RjwECA/edit). 

Updating and deleting can optionally be done later, as those are part of the third ("Seasoned") milestone as listed in the [Roadmap](https://docs.google.com/document/d/1tEaWovAlEpwyuWLxEuzlnQ0ikDHKllNR5J6L-Gzad48/edit) (and Updating requires a decision to be made per the document)

**Comment by shubhamdixit863** [comment]
I will take up this issue
