### ISSUE TITLE
Server Side Apply

### ISSUE THREAD

**Issue by juliev0** [numaproj-labs/numaplane#38]
We're currently using Client-side Apply for applying objects. K8S seems to be moving from client-side apply to server-side apply, which seems to be good for this case: another Controller is doing an "apply" as opposed to a standard "update" or "patch". If both Numaplane and that other Controller were to do "client side apply", then they'd mess each other up, overriding each other's fields.

This doesn't seem urgent, however, as I'm pretty sure the Controllers we interoperate with don't use "client side apply" (Numaflow Controllers plus standard K8S Controllers).

**Comment by xdevxy** [comment]
Closed as no longer applicable with refactor.
