### ISSUE TITLE
Verify that if a Resource is updated in the middle of Get-then-patch it will get a conflict failure

### ISSUE THREAD

**Issue by juliev0** [numaproj-labs/numaplane#39]
Test to make sure that if a Resource is updated in between [util.GetModifiedConfiguration()](https://github.com/numaproj-labs/numaplane/blob/main/internal/kubernetes/client.go#L76) and `patcher.Patch()` that it will get a conflict error and automatically retry. 

(Can use dlv debugger to set the breakpoint)

**Comment by chandankumar4** [comment]
Verified this issue and did not get any conflict error, Attached few image for reference

numaplane-controller log

<img width="1921" alt="Screenshot 2024-01-25 at 3 07 07 PM" src="https://github.com/numaproj-labs/numaplane/assets/28861964/95b6e223-193f-4178-8102-0fda1c9f4ec7">

Debugger Point
<img width="1137" alt="Screenshot 2024-01-25 at 3 08 16 PM" src="https://github.com/numaproj-labs/numaplane/assets/28861964/b1d0e0f5-8a12-4fc2-b70f-7a26a20825be">

Modified nginx apps manually in cluster at debuuger point
```
macos-P9DJ3XY0QL :: ~ » k edit deploy nginx -n numaplane-system
deployment.apps/nginx edited
macos-P9DJ3XY0QL :: ~ » k edit deploy nginx -n numaplane-system
deployment.apps/nginx edited
```

**Comment by juliev0** [comment]
If one sets a breakpoint directly before `Patcher.patchSimple()` applies the patch (after it has calculated it), and then allows another to update the Resource at the same time, if the two are setting different fields, then the result will be a combination of the two definitions.

I repeated the same thing just using `kubectl apply` in two places at the same time. 

First prior to the test, I actually deployed this spec:
```
apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
  name: simple-pipeline
spec:
  vertices:
    - name: in
      source:
        # A self data generating source
        generator:
          rpu: 5
          duration: 10s
    - name: cat
      udf:
        builtin:
          name: cat # A built-in UDF which simply cats the message
    - name: out
      sink:
        # A simple log printing sink
        log: {}
  edges:
    - from: in
      to: cat
    - from: cat
      to: out
  limits:
    # nothing here
```

Then I deployed pipeline spec 1 while setting the breakpoint (Note field `bufferMaxLength`):

```
apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
  name: simple-pipeline
spec:
  vertices:
    - name: in
      source:
        # A self data generating source
        generator:
          rpu: 5
          duration: 10s
    - name: cat
      udf:
        builtin:
          name: cat # A built-in UDF which simply cats the message
    - name: out
      sink:
        # A simple log printing sink
        log: {}
  edges:
    - from: in
      to: cat
    - from: cat
      to: out
  limits:
    bufferMaxLength: 50000
```



Then I deployed pipeline spec 2 (note this sets a different field `bufferUsageLimit`) and allowed it go through:

```
apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
  name: simple-pipeline
spec:
  vertices:
    - name: in
      source:
        # A self data generating source
        generator:
          rpu: 5
          duration: 10s
    - name: cat
      udf:
        builtin:
          name: cat # A built-in UDF which simply cats the message
    - name: out
      sink:
        # A simple log printing sink
        log: {}
  edges:
    - from: in
      to: cat
    - from: cat
      to: out
  limits:
    bufferUsageLimit: 10
```

Result:
Both applies happen without error. The result is this spec:
```
apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"numaflow.numaproj.io/v1alpha1","kind":"Pipeline","metadata":{"annotations":{},"name":"simple-pipeline","namespace":"numaflow-pipeline"},"spec":{"edges":[{"from":"in","to":"cat"},{"from":"cat","to":"out"}],"limits":{"bufferMaxLength":50000},"vertices":[{"name":"in","source":{"generator":{"duration":"10s","rpu":5}}},{"name":"cat","udf":{"builtin":{"name":"cat"}}},{"name":"out","sink":{"log":{}}}]}}
  creationTimestamp: "2024-01-27T02:24:16Z"
  finalizers:
  - pipeline-controller
  generation: 4
  name: simple-pipeline
  namespace: numaflow-pipeline
  resourceVersion: "924281"
  uid: c4948428-1596-4209-8065-f81194f5a621
spec:
  edges:
  - from: in
    to: cat
  - from: cat
    to: out
  lifecycle:
    deleteGracePeriodSeconds: 30
    desiredPhase: Running
  limits:
    bufferMaxLength: 50000
    bufferUsageLimit: 10
    readBatchSize: 500
    readTimeout: 1s
  vertices:
  - name: in
    source:
      generator:
        duration: 10s
        msgSize: 8
        rpu: 5
  - name: cat
    udf:
      builtin:
        name: cat
  - name: out
    sink:
      log: {}
  watermark:
    disabled: false
    maxDelay: 0s
```

**Comment by juliev0** [comment]
Note in the above, that "last-applied-configuration" simply gets set to what it was set to be in Spec 1. 

From here, self healing will also not cause a patch to look at this field (if it's not setting it). As you can see, I can do a subsequent test in which I apply a similar definition to Spec 1 except just change `bufferMaxLength: 3000` (not touching `bufferUsageLimit`). The net result is:
```
apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"numaflow.numaproj.io/v1alpha1","kind":"Pipeline","metadata":{"annotations":{},"name":"simple-pipeline","namespace":"numaflow-pipeline"},"spec":{"edges":[{"from":"in","to":"cat"},{"from":"cat","to":"out"}],"limits":{"bufferMaxLength":50000},"vertices":[{"name":"in","source":{"generator":{"duration":"10s","rpu":5}}},{"name":"cat","udf":{"builtin":{"name":"cat"}}},{"name":"out","sink":{"log":{}}}]}}
  creationTimestamp: "2024-01-27T02:24:16Z"
  finalizers:
  - pipeline-controller
  generation: 4
  name: simple-pipeline
  namespace: numaflow-pipeline
  resourceVersion: "1111030"
  uid: c4948428-1596-4209-8065-f81194f5a621
spec:
  edges:
  - from: in
    to: cat
  - from: cat
    to: out
  lifecycle:
    deleteGracePeriodSeconds: 30
    desiredPhase: Running
  limits:
    bufferMaxLength: 50000
    bufferUsageLimit: 10
    readBatchSize: 500
    readTimeout: 1s
  vertices:
  - name: in
    source:
      generator:
        duration: 10s
        msgSize: 8
        rpu: 5
  - name: cat
    udf:
      builtin:
        name: cat
  - name: out
    sink:
      log: {}
  watermark:
    disabled: false
    maxDelay: 0s
```

**Comment by xdevxy** [comment]
> Note in the above, that "last-applied-configuration" simply gets set to what it was set to be in Spec 1.
> 
> From here, self healing will also not cause a patch to look at this field (if it's not setting it). As you can see, I can do a subsequent test in which I apply a similar definition to Spec 1 except just change `bufferMaxLength: 3000` (not touching `bufferUsageLimit`). The net result is:
> 
> ```
> apiVersion: numaflow.numaproj.io/v1alpha1
> kind: Pipeline
> metadata:
>   annotations:
>     kubectl.kubernetes.io/last-applied-configuration: |
>       {"apiVersion":"numaflow.numaproj.io/v1alpha1","kind":"Pipeline","metadata":{"annotations":{},"name":"simple-pipeline","namespace":"numaflow-pipeline"},"spec":{"edges":[{"from":"in","to":"cat"},{"from":"cat","to":"out"}],"limits":{"bufferMaxLength":50000},"vertices":[{"name":"in","source":{"generator":{"duration":"10s","rpu":5}}},{"name":"cat","udf":{"builtin":{"name":"cat"}}},{"name":"out","sink":{"log":{}}}]}}
>   creationTimestamp: "2024-01-27T02:24:16Z"
>   finalizers:
>   - pipeline-controller
>   generation: 4
>   name: simple-pipeline
>   namespace: numaflow-pipeline
>   resourceVersion: "1111030"
>   uid: c4948428-1596-4209-8065-f81194f5a621
> spec:
>   edges:
>   - from: in
>     to: cat
>   - from: cat
>     to: out
>   lifecycle:
>     deleteGracePeriodSeconds: 30
>     desiredPhase: Running
>   limits:
>     bufferMaxLength: 50000
>     bufferUsageLimit: 10
>     readBatchSize: 500
>     readTimeout: 1s
>   vertices:
>   - name: in
>     source:
>       generator:
>         duration: 10s
>         msgSize: 8
>         rpu: 5
>   - name: cat
>     udf:
>       builtin:
>         name: cat
>   - name: out
>     sink:
>       log: {}
>   watermark:
>     disabled: false
>     maxDelay: 0s
> ```

So the subsequent test was not able to set` bufferMaxLength: 3000`? Do you get an error for that apply?

**Comment by juliev0** [comment]
@xdevxy No error. This is because it takes the “last-applied-configuration” which doesn’t include the field, and it takes the new spec, which also doesn’t include the field, and takes a diff. This diff doesn’t say anything about that field because in its mind, it didn’t change.

It may be that SSA is supposed to address this problem among others. I will investigate

**Comment by juliev0** [comment]
What's weird is that this medium [article](https://medium.com/swlh/break-down-kubernetes-server-side-apply-5d59f6a14e26) seems to suggest that some different behavior should happen:

"If the object exists when executing kubectl apply, it will convert to update.

If two users submit the update simultaneously, only one of them will succeed and then update the resourceVersion. And the other is required to update the local object and submit again."

**Comment by juliev0** [comment]
closing - will explore Server Side Apply next

**Comment by juliev0** [comment]
I spoke to someone from ArgoCD. I don't believe they actually do use _resourceVersion_ in their patch after all, although he was suggesting that we could. (I did try doing this before: one thing that happens is that it then gets incorporated into "last-applied-configuration" annotation, and then if anyone tries to do a kubectl apply going forward (with no _resourceVersion_ in the spec), K8S will think they're trying to remove that field and then reject the request - not sure if that's a good thing or a bad thing that nobody can do a kubectl apply (example of someone who got into this situation [here](https://stackoverflow.com/questions/71581444/how-to-fix-metadata-resourceversion-invalid-value-must-be-specified-for-an)). In any case, ArgoCD doesn't set _resourceVersion_ in their patch after all, and they don't worry about it.  They figure that they are only responsible for the fields that they set. If someone else sets something, they don't worry about it.
[3:40](https://intuit-teams.slack.com/archives/C05K82P3N9J/p1706917227124809)
So, if we follow ArgoCD's mindset, then we don't worry about it.
