### ISSUE TITLE
Create goroutine which starts up and clones a git repository

### ISSUE THREAD

**Issue by juliev0** [numaproj-labs/numaplane#4]
Depends on #3 

Create a goroutine in GitSyncProcessor which will be used to sync a git repository. It will take a repository name and path, and an optional previous git commit hash. For now, just start up and clone the path. We assume whatever the main branch is.

If the previous git commit hash is passed in, clone the repository at that hash. If not, clone it at the latest HEAD.

Call the create and update functions described [here](https://github.com/numaproj-labs/numaplane/issues/5) depending on whether the resource already exists or not (if that work hasn't been done yet, just create no-op methods for those).

**Comment by juliev0** [comment]
if you comment Shubham, we can assign to you

**Comment by shubhamdixit863** [comment]
please assign me

**Comment by juliev0** [comment]
Per our discussion, it's fine if this part occurs outside of the goroutine too.

**Comment by chandankumar4** [comment]
yes, I'll provide a wrapper for `Apply()`, which will take []byte and call `Apply()` internally
