### ISSUE TITLE
Consider replacing default Logger

### ISSUE THREAD

**Issue by juliev0** [numaproj-labs/numaplane#6]
We used kubebuilder to scaffold this repository, per [this](https://book.kubebuilder.io/quick-start) guide. It uses [this](https://github.com/go-logr/logr) Logger, which takes the stance of simplicity and doesn't have the usual functionality we're used to ("debug" and "warn" functions for example). Consider replacing the logger with zap.SugaredLogger, which is used in numaflow.

**Comment by chandankumar4** [comment]
I'll work on this issue

**Comment by xdevxy** [comment]
Close this as #8 is merged
