### ISSUE TITLE
'object not found' error when watching a repo

### ISSUE THREAD

**Issue by xdevxy** [numaproj-labs/numaplane#69]
When watching a repo, periodically getting the following errors running in a local cluster,
```
{"level":"error","ts":"2024-01-31T00:53:47.905628359Z","logger":"numaplane","caller":"git/gitsync_processor.go:179","msg":"checking for new updates err","GitSync name":"gitsync-example","RepositoryPath Name":"user-repo","err":"object not found","stacktrace":"github.com/numaproj-labs/numaplane/internal/git.watchRepo\n\t/workspace/internal/git/gitsync_processor.go:179\ngithub.com/numaproj-labs/numaplane/internal/git.NewGitSyncProcessor.func1\n\t/workspace/internal/git/gitsync_processor.go:481"}
{"level":"error","ts":"2024-01-31T00:53:47.905639776Z","logger":"numaplane","caller":"git/gitsync_processor.go:484","msg":"error watching the repo","err":"object not found","stacktrace":"github.com/numaproj-labs/numaplane/internal/git.NewGitSyncProcessor.func1\n\t/workspace/internal/git/gitsync_processor.go:484"}
```

**Comment by juliev0** [comment]
So, you think the object being referred to is the GitSync itself? On which line are we referring to it that would cause the problem?

**Comment by juliev0** [comment]
It does seem problematic that we are referring to `status.CommitStatus` in `CheckForRepoUpdates()` if that's what you're referring to. I think we should just be saving the lastCommitStatus in the object so we don't need to do a `Get` to the API every 3 minutes.

**Comment by juliev0** [comment]
You could actually just store the lastCommitHash locally on the stack too. Instead of calling:
```
CheckForRepoUpdates(ctx, r, repo, &gitSync.Status, namespace)
```
you could call:
```
CheckForRepoUpdates(ctx, r, repo, &lastCommitHash, namespace)
```

**Comment by xdevxy** [comment]
yeah, exactly

> You could actually just store the lastCommitHash locally on the stack too. Instead of calling:
> 
> ```
> CheckForRepoUpdates(ctx, r, repo, &gitSync.Status, namespace)
> ```
> 
> you could call:
> 
> ```
> CheckForRepoUpdates(ctx, r, repo, &lastCommitHash, namespace)
> ```
> 
> Or..I do see that you are returning the hash currently, so if you want to continue doing that, then pass it by value:
> 
> ```
> CheckForRepoUpdates(ctx, r, repo, lastCommitHash, namespace)
> ```
> 
> but in any case you can just maintain the value locally within the goroutine.

Yeah, exactly.

**Comment by xdevxy** [comment]
Closed by https://github.com/numaproj-labs/numaplane/pull/71
