### ISSUE TITLE
Authn/authz setup for accessing a git repository

### ISSUE THREAD

**Issue by xdevxy** [numaproj-labs/numaplane#9]
Numaplane ConfigMap should contain any Git Repository Prefix that has credentials for repositories nested within. For any given repository, there may or may not be a matching prefix in there. If there is no matching entry, then no credentials are needed for cloning that RepositoryPath.

For any entry in that ConfigMap, it may contain:
- no credentials
- SSHCredential only
- HTTPCredential only
- TLSCredential only (theoretically I think this should be possible even if it's never used in practice?)
- SSHCredential, HTTPCredential
- SSHCredential, TLSCredential
- HTTPCredential, TLSCredential
- SSHCredential, HTTPCredential, TLSCredential

Our RepositoryPath contains a protocol in it ("ssh" or "http" or "https" (or maybe another one but let's at least support these)). Based on that protocol, we need to see if there is an "HTTPCredential" or "SSHCredential". 

For "https" there should also be a TLSCredential. For "http" there should not. For "ssh" there could potentially be a TLSCredential.

**Comment by chandankumar4** [comment]
i'll work on it :)

**Comment by juliev0** [comment]
@xdevxy what are the details here? Basically we need to store github credentials in a Secret or something? In order for @shubhamdixit863 to test https://github.com/numaproj-labs/numaplane/issues/4, he will need to use some sort of github credentials anyway, right? But perhaps he won't need to store them in a Secret, and that can be the work of this Issue? Is that what you have in mind?

**Comment by xdevxy** [comment]
Yeah @shubhamdixit863 can use a public repo for testing to start.

**Comment by juliev0** [comment]
> Yeah @shubhamdixit863 can use a public repo for testing to start.

Oh, okay. No credentials required in that case I guess. 

So, for this feature the RepositoryPaths in the CRD can each include an optional Secret containing credentials, or something like that.

**Comment by xdevxy** [comment]
Yeah, right, updating the issue's description to reflect that.

**Comment by juliev0** [comment]
@shubhamdixit863 In the RepositoryPath you can include a Secret similar to [this](https://github.com/numaproj/numaflow/blob/main/pkg/apis/numaflow/v1alpha1/redis_buffer_service.go#L50) one used by Numaflow RedisBufferService

@xdevxy which [authentication](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/about-authentication-to-github) methods will we offer (initially)?

**Comment by xdevxy** [comment]
I'm thinking about using access token to start with, https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens, which it would be easy to grant and revoke the access.

**Comment by juliev0** [comment]
> I'm thinking about using access token to start with, https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens, which it would be easy to grant and revoke the access.

That sounds good. I believe an Access Token is considered a "password" of sorts.

**Comment by juliev0** [comment]
@shubhamdixit863 I looked up how ArgoCD handles credentials, and they actually don't reference these Secrets within the CR itself - rather, it's an application-wide thing. They basically have the capability of associating a Git URL Prefix (such as "https://github.intuit.com") with a set of Credentials (i.e. a Secret). If we take this approach, this would mean that people don't need to set all of their GitSync CRs to reference the Secret. I guess the other upside is that you could change the Secret name and only change the reference in one place. 

@xdevxy and I spoke of how you can initially start to work on getting the username/Access Token working (have you logged into https://github.intuit.com, which is one repo you could try it out on?) and then we can work on incorporating a ConfigMap for the Controller to read.

Are we using this [Endpoint](https://pkg.go.dev/github.com/go-git/go-git/v5@v5.11.0/plumbing/transport#Endpoint) struct in our code currently? I see it offers Username and Password.  If you end up getting a TLS error like `x509: certificate signed by unknown authority`, we may also need set the `InsecureSkipTLS` field there.

**Comment by juliev0** [comment]
@shubhamdixit863 I added [this](https://github.com/numaproj-labs/numaplane/issues/79) issue, since @xdevxy and I discussed that we can use the same approach as ArgoCD and have a universal mapping of RepositoryPathPrefix to credentials, rather than having somebody define their credentials on each GitSync CR itself.

**Comment by xdevxy** [comment]
Closed by #118
